#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#spring.application.name=api-gateway
#server.port=8989
#server.address=192.168.1.203
#
#logging.level.root=INFO
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
#logging.level.org.springframework.cloud.gateway=TRACE
#
##Product Service Routes
#spring.cloud.gateway.routes[0].id=product-service
#spring.cloud.gateway.routes[0].uri=lb://product-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products
#
##Order Service Routes
#spring.cloud.gateway.routes[1].id=order-service
#spring.cloud.gateway.routes[1].uri=lb://order-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders

server:
  port: 8989
  address: 192.168.1.203

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: DEBUG
